version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: euro2025-app
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    networks:
      - euro2025-net

networks:
  euro2025-net:
    driver: bridge